### ISSUE TITLE
I'm getting some errors

### ISSUE THREAD

**Issue by Leinad4Mind** [ForumHulp/statistics#16]
Hi there forumhulp. I found a lot of this kind of two errors in my logs:

`PHP Fatal error:  Uncaught Error: Undefined class constant 'PLATFORM_WINDOWS_CE' in /var/www/html/forum-may2018/ext/forumhulp/statistics/vendor/find_os.php:409\nStack trace:\n#0 /var/www/html/forum-may2018/ext/forumhulp/statistics/vendor/find_os.php(214): find_os->checkBrowserInternetExplorer()\n#1 /var/www/html/forum-may2018/ext/forumhulp/statistics/vendor/find_os.php(114): find_os->checkBrowsers()\n#2 /var/www/html/forum-may2018/ext/forumhulp/statistics/vendor/find_os.php(74): find_os->determine()\n#3 /var/www/html/forum-may2018/ext/forumhulp/statistics/cron/task/core/prune_statistics.php(79): find_os->setUserAgent('PocketParser/2....')\n#4 [internal function]: forumhulp\\statistics\\cron\\task\\core\\prune_statistics->run()\n#5 /var/www/html/forum-may2018/phpbb/cron/task/wrapper.php(104): call_user_func_array(Array, Array)\n#6 /var/www/html/forum-may2018/cron.php(78): phpbb\\cron\\task\\wrapper->__call('run', Array)\n#7 {main}\n  thrown in /var/www/html/forum-may2018/ext/forumhulp/statistics/vendor/find_os.php on line 409, referer: `

Plus this one:
`PHP Fatal error:  SQL ERROR [ mysqli ]<br /><br />Column 'ip_addr' cannot be null [1048]<br /><br />An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists. in /var/www/html/forum-may2018/phpbb/db/driver/driver.php on line 996`

**Comment by ForumHulp** [comment]
That's not good, i will look at it soon

**Comment by Leinad4Mind** [comment]
Any news about how to truncate the table? It should have a prune setting. Where is it?
